#!/bin/bash

if [ ! -f /emulator-data/rpi.img ]; then
  cd /emulator-data
  wget https://downloads.raspberrypi.org/raspbian_latest
  unzip raspbian_latest
  mv ./*.img rpi.img
  rm raspbian_latest

  # modify https://www.linux-tips-and-tricks.de/de/raspberry/22-wie-kann-man-raspberry-pi-unter-kvm-emulieren
  IMAGE_OFFSET=`expr 512 * 94208`  # 94208 startsector second partition
  mount /emulator-data/rpi.img -o offset=$IMAGE_OFFSET /mnt
  echo '' > /mnt/etc/ld.so.preload
  umount /mnt
  cd -
fi

if [ ! -d /emulator-data/qemu-rpi-kernel ]; then
  cd /emulator-data
  git clone https://github.com/dhruvvyas90/qemu-rpi-kernel.git
  cd -
fi
