version: '2'

services:
  base:
    build: ./config/docker/base
    image: rpi_base:latest
    container_name: base

  wiringpi:
    # uses rpi_base:latest as base image
    build: ./config/docker/wiringpi
    volumes:
      - /:/host
    depends_on:
      - base
